# render.yaml
# This file defines the web service for the reelnn-backend.
# The database will be hosted on MongoDB Atlas and connected via an environment variable.

services:
  # The Web Service (Node.js Backend)
  - type: web
    name: reelnn-backend
    runtime: node
    plan: free # Use the free instance type
    repo: https://github.com/AgPirosbabws/reelnn-backend
    branch: main
    
    # Build and Start Commands
    buildCommand: "npm install"
    startCommand: "node server.js"

    # Environment Variables
    # NOTE: The MONGO_URI must be added manually in the Render dashboard
    # after connecting to a free MongoDB Atlas database.
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_SECRET
        generateValue: true # Render will securely generate a random value for this.
